// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutionService.proto

package org.Executors;

public interface ExecutionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.Executors.ExecutionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string className = 1;</code>
   * @return The className.
   */
  java.lang.String getClassName();
  /**
   * <code>string className = 1;</code>
   * @return The bytes for className.
   */
  com.google.protobuf.ByteString
      getClassNameBytes();

  /**
   * <code>string methodName = 2;</code>
   * @return The methodName.
   */
  java.lang.String getMethodName();
  /**
   * <code>string methodName = 2;</code>
   * @return The bytes for methodName.
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <code>string jarLocation = 3;</code>
   * @return The jarLocation.
   */
  java.lang.String getJarLocation();
  /**
   * <code>string jarLocation = 3;</code>
   * @return The bytes for jarLocation.
   */
  com.google.protobuf.ByteString
      getJarLocationBytes();

  /**
   * <code>string data = 4;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
