// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutionService.proto

package org.Executors;

public interface ExecutionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.Executors.ExecutionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string errCode = 1;</code>
   * @return The errCode.
   */
  java.lang.String getErrCode();
  /**
   * <code>string errCode = 1;</code>
   * @return The bytes for errCode.
   */
  com.google.protobuf.ByteString
      getErrCodeBytes();

  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
